
def run(latex_path):

    # tags = [("Title", "TitleTitle1 Intermittent Faults Diagnosis in Multi-Agent Systems"),
    #         ("AbstractSection", ""),
    #         ("AbstractPar", "AbstractBegin Multi-Agent Systems (MAS) can be",
    #          "nd that it outperforms SFL-based algorithms"),
    #         ("Figure", "1"),
    #         ("CaptionFigure", "CaptionCaption1: Visualization shown in Table 1",
    #          "CaptionCaption1: Visualization shown in Table 1."),
    #         ("Section", "SectionSection1"),
    #         ("Par", "ParagParag1 Systems (MAS) can be found in a w", "working without accidents."),
    #         ("Par", "ParagParag2 can occasionally fail achiev",
    #          "executing a re-planing process or performing other recovery operations."),
    #         ("Par", "ParagParag3: The generation of IFDMAS", "FDMAS problems consists of the following steps:"),
    #         ("Enum", " ENUM1 Create synthetic maps or use benchmark", " obtain the set of resources R."),
    #         ("Enum", "ENUM2 Set a group of m agents a", "2 time steps (m is a parameter)."),
    #         ("Enum", "ENUM3 Generate the agents’ plan by runnin", "a MAPF algorithm."),
    #         ("Enum", "ENUM4 Set x faulty agents with a probability of p", "ility of p delaying at any resource durin."),
    #         ("Enum", " ENUM5 Set the critical resource", "d add them t"),
    #         ("Par", "ParagParag3 address intermittent faults in MAS", "problem in terms of Model-Based Diagnosis."),
    #         ("Par", "ParagParag4 second contribution is by presenting a", "od based on this observation."),
    #         ("Par", "ParagParag5 evaluate MGSD on", "er SFL algorithms."),
    #         ("Section", "SectionSection2"),
    #         ("Par", "ParagParag6 of MAS failures has been studied in previous",
    #          "ous work regarding coordination failures and MAP failures."),
    #         ("SubSection", "SubSection1-Based Diagnosis Background"),
    #         ("Par", "ParagParag7-Based Diagnosis (MBD) prob", "mponents as indicated by certain observations."),
    #         ("Definition", "(DefDef1) An MBD problem is specified by", "This is expressed formally as follows:"),
    #         ("Formula", "1"),
    #         ("Par", "ParagParag8, like us, ", "but rather model their plans."),
    #         ("Par", "ParagParag9 diagnosis ∆ ⊆ A is defined as:", "ParagParag9 diagnosis ∆ ⊆ A is defined as:"),
    #         ("Formula", "2"),
    #         ("Par", "ParagParag10 noting that the diagnosis", "FDMAS problem."),
    #         ("Definition", "(DefDef2) Given an agent aj ∈ A and a gam", "resource and F alse otherwise. Formally,"),
    #         ("Formula", "3"),
    #         ("Figure", "2"),
    #         ("Figure", "3"),
    #         ("Par", "ParagParag11, like us, use an SFL-based appro", "model, which is typically diffi"),
    #         ("Formula", "4"),
    #         ("Section", "SectionSection3"),
    #         ("Table", "1"),
    #         ("CaptionTable", "CaptionCaption2 A Scenario that shows the For", "e plan of each agent."),
    #         ("Par", "ParagParag12 are few motivating examples in",
    #          "ehicles (AGV) is tasked with moving racks between locations.")
    #         ]
    #
    # lines_to_search = [
    #     ("Title", "TitleTitle1 Intermittent Faults Diagnosis in Multi-Agent Systems"),
    #     ("AbstractSection", "Abstract"),
    #     (
    #     "AbstractPar", "AbstractBegin Multi-Agent Systems (MAS) can be", "nd that it outperforms SFL-based algorithms"),
    #     ("CaptionFigure", "Figure CaptionCaption1: Visualization shown in Table 1",
    #      "CaptionCaption1: Visualization shown in Table 1."),
    #     ("Section", "SectionSection1"),
    #     ("Par", "ParagParag1 Systems (MAS) can be found in a w", "working without accidents."),
    #     ("Par", "ParagParag2 can occasionally fail achiev",
    #      "executing a re-planing process or performing other recovery operations."),
    #     ("Par", "ParagParag3: The generation of IFDMAS", "FDMAS problems consists of the following steps:"),
    #     ("Enum", " ENUM1 Create synthetic maps or use benchmark", " obtain the set of resources R."),
    #     ("Enum", "ENUM2 Set a group of m agents a", "2 time steps (m is a parameter)."),
    #     ("Enum", "ENUM3 Generate the agents’ plan by runnin", "a MAPF algorithm."),
    #     ("Enum", "ENUM4 Set x faulty agents with a probability of p", "ility of p delaying at any resource durin."),
    #     ("Enum", " ENUM5 Set the critical resource", "d add them t"),
    #     ("Par", "ParagParag3 address intermittent faults in MAS", "problem in terms of Model-Based Diagnosis."),
    #     ("Par", "ParagParag4 second contribution is by presenting a", "od based on this observation."),
    #     ("Par", "ParagParag5 evaluate MGSD on", "er SFL algorithms."),
    #     ("Section", "SectionSection2"),
    #     ("Par", "ParagParag6 of MAS failures has been studied in previous",
    #      "ous work regarding coordination failures and MAP failures."),
    #     ("SubSection", "SubSection1-Based Diagnosis Background"),
    #     ("Par", "ParagParag7-Based Diagnosis (MBD) prob", "mponents as indicated by certain observations."),
    #     ("Definition", "Definition (DefDef1) An MBD problem is specified by", "This is expressed formally as follows:"),
    #     ("Par", "ParagParag8, like us, ", "but rather model their plans."),
    #     ("Par", "ParagParag9 diagnosis ∆ ⊆ A is defined as:", "ParagParag9 diagnosis ∆ ⊆ A is defined as:"),
    #     ("Par", "ParagParag10 noting that the diagnosis", "FDMAS problem."),
    #     ("Definition", "Definition (DefDef2) Given an agent aj ∈ A and a gam",
    #      "resource and F alse otherwise. Formally,"),
    #     ("Par", "ParagParag11, like us, use an SFL-based appro", "model, which is typically diffi"),
    #     ("Section", "SectionSection3"),
    #     ("CaptionTable", "Table CaptionCaption2 A Scenario that shows the For", "e plan of each agent."),
    #     ("Par", "ParagParag12 are few motivating examples in",
    #      "ehicles (AGV) is tasked with moving racks between locations."),
    #     ("END", "END", "END")
    # ]

    tags = [("Title", "TitleTitle1 Intermittent Faults Diagnosis in Multi-Agent Systems"),
            ("AbstractSection", ""),
            ("AbstractPar", "AbstractBegin Multi-Agent Systems (MAS) can be",
             "nd that it outperforms SFL-based algorithms"),
            ("Figure", "1"),
            ("CaptionFigure", "CaptionCaption1: Visualization shown in Table 1",
             "CaptionCaption1: Visualization shown in Table 1."),
            ("Section", "SectionSection1"),
            ("Par", "ParagParag1 Systems (MAS) can be found in a w", "working without accidents."),
            ("Matrix","1"),
            ("Par", "ParagParag2 can occasionally fail achiev",
             "executing a re-planing process or performing other recovery operations."),
            ("Par", "ParagParag3: The generation of IFDMAS", "FDMAS problems consists of the following steps:"),
            ("Enum", " ENUM1 Create synthetic maps or use benchmark", " obtain the set of resources R."),
            ("Enum", "ENUM2 Set a group of m agents a", "2 time steps (m is a parameter)."),
            ("Enum", "ENUM3 Generate the agents’ plan by runnin", "a MAPF algorithm."),
            ("Enum", "ENUM4 Set x faulty agents with a probability of p", "ility of p delaying at any resource durin."),
            ("Enum", " ENUM5 Set the critical resource", "d add them t"),
            ("Par", "ParagParag3 address intermittent faults in MAS", "short period of time may result in inaccurate diagnosis."),
            ("Formula","1"),
            ("Par", "Therefore, the MAS should be observed throughout", "roblem in terms of Model-Based Diagnosis."),
            ("Par", "ParagParag5 evaluate MGSD on", "er SFL algorithms."),
            ("Section", "SectionSection2"),
            ("Par", "ParagParag6 of MAS failures has been studied in previous",
             "ous work regarding coordination failures and MAP failures."),
            ("SubSection", "SubSection1-Based Diagnosis Background"),
            ("Definition", "(DefDef1) An MBD problem is specified by", "This is expressed formally as follows:"),
            ("Formula", "2"),
            ("Definition", "(DefDef2) An MBD problem is specified by", "This is expressed formally as follows:"),
            ("Formula", "3"),

            ("Par", "ParagParag8, like us, ", "but rather model their plans."),
            ("Par", "ParagParag9 diagnosis ∆ ⊆ A is defined as:", "ParagParag9 diagnosis ∆ ⊆ A is defined as:"),
            ("Formula", "4"),
            ("Definition", "(DefDef3) Given an agent aj ∈ A and a gam", "resource and F alse otherwise. Formally,"),
            ("Formula", "5"),
            ("Figure", "2"),
            ("Figure", "3"),
            ("Figure", "4"),
            ("Figure", "5"),
            ("Par", "ParagParag11, like us, use an SFL-based appro", "model, which is typically diffi"),
            ("Algorithm", "7"),
            ("Section", "SectionSection3"),
            ("Algorithm", "8"),
            ]

    lines_to_search  = [
        ("Title", "TitleTitle1 Intermittent Faults Diagnosis in Multi-Agent Systems"),
            ("AbstractSection", "Abstract"),
            ("AbstractPar", "AbstractBegin Multi-Agent Systems (MAS) can be",
             "nd that it outperforms SFL-based algorithms"),
            ("CaptionFigure", "Figure CaptionCaption1: Visualization shown in Table 1",
             "CaptionCaption1: Visualization shown in Table 1."),
            ("Section", "SectionSection1"),
            ("Par", "ParagParag1 Systems (MAS) can be found in a w", "working without accidents."),
            ("Par", "ParagParag2 can occasionally fail achiev",
             "executing a re-planing process or performing other recovery operations."),
            ("Par", "ParagParag3: The generation of IFDMAS", "FDMAS problems consists of the following steps:"),
            ("Enum", " ENUM1 Create synthetic maps or use benchmark", " obtain the set of resources R."),
            ("Enum", "ENUM2 Set a group of m agents a", "2 time steps (m is a parameter)."),
            ("Enum", "ENUM3 Generate the agents’ plan by runnin", "a MAPF algorithm."),
            ("Enum", "ENUM4 Set x faulty agents with a probability of p", "ility of p delaying at any resource durin."),
            ("Enum", " ENUM5 Set the critical resource", "d add them t"),
            ("Par", "ParagParag3 address intermittent faults in MAS", "short period of time may result in inaccurate diagnosis."),
            ("Par", "Therefore, the MAS should be observed throughout", "roblem in terms of Model-Based Diagnosis."),
            ("Par", "ParagParag5 evaluate MGSD on", "er SFL algorithms."),
            ("Section", "SectionSection2"),
            ("Par", "ParagParag6 of MAS failures has been studied in previous",
             "ous work regarding coordination failures and MAP failures."),
            ("SubSection", "SubSection1-Based Diagnosis Background"),
            ("Definition", "Definition (DefDef1) An MBD problem is specified by", "This is expressed formally as follows:"),
            ("Definition", "Definition (DefDef2) An MBD problem is specified by", "This is expressed formally as follows:"),
            ("Par", "ParagParag8, like us, ", "but rather model their plans."),
            ("Par", "ParagParag9 diagnosis ∆ ⊆ A is defined as:", "ParagParag9 diagnosis ∆ ⊆ A is defined as:"),
            ("Definition", "Definition (DefDef3) Given an agent aj ∈ A and a gam", "resource and F alse otherwise. Formally,"),
            ("Par", "ParagParag11, like us, use an SFL-based appro", "model, which is typically diffi"),
            ("Section", "SectionSection3"),
        ("END", "END", "END")
    ]

    return (tags,lines_to_search)


if __name__=="__main__":
    path = '../../pdf-tests/two_pages_with_specific_v3.tex'
    ans= run(path)
    print(ans)
    # ans = parse(path)
    #
    # for i in ans:
    #     print(f"{i}: {ans[i]}")
